config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
  resources :activities
  get 'home/welcome'
  root 'home#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :activities
  has_one :profile
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    #@activity = Activity.new
    @activity = current_user.activities.build
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    #@activity = Activity.new(activity_params)
    @activity = current_user.activities.build(activity_params)
    
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @activity = current_user.activities.find_by(id: params[:id])
    redirect_to activities_path, notice: "No permission to do that!" if @activity.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:title, :description, :date_time, :distance, :elapsed_time, :elevation, :avg_hr, :max_hr, :effort, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  # Still need to check if this before_action(s) are right...
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]



  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :age, :nactionality, :gender, :photo)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field-lay">
<div class="field-edt">
  <div class="field">
   <%= form.label :title %>
   <%= form.text_field :title, class:"form-control", id:"exampleFormControlTextarea1" %>
  </div>

  <div class="field-d-t">
   <%= form.label :date_time %>
   <%= form.datetime_select :date_time %>
  </div>
 
  <div class="field-d-t">
   <%= form.label :elapsed_time %>
    <%= form.time_select :elapsed_time %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.text_field :distance, class:"form-control", id:"exampleFormControlTextarea1" %>
  </div>

  <div class="field-e-m-a-e">
    <%= form.label :elevation %>
    <%= form.number_field :elevation, class:"form-control", id:"exampleFormControlTextarea1" %>
  </div>

  <div class="field-e-m-a-e">
    <%= form.label :avg_hr %>
    <%= form.number_field :avg_hr, class:"form-control", id:"exampleFormControlTextarea1" %>
  </div>

  <div class="field-e-m-a-e">
    <%= form.label :max_hr %>
    <%= form.number_field :max_hr, class:"form-control", id:"exampleFormControlTextarea1" %>
  </div>

  <div class="field-e-m-a-e">
    <%= form.label :effort %>
    <%= form.number_field :effort, class:"form-control", id:"exampleFormControlTextarea1" %>
  </div>

  <div class="field">
   <%= form.label :description %>
   <%= form.text_area :description, class:"form-control", id:"exampleFormControlTextarea1" %>
  </div> 

  <div class="field">
    <%= form.number_field :user_id, id: :activity_user_id, value: current_user.id, type: :hidden %>
  </div>

</div>
<div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div class="activity-mainbody">
  <div class="activity-userinfo">
   <div class="activity-user">
     <h4>Name user</h4><br>
     <div class="activity-avatar-u">
       <img src="" alt="img">
     </div>
   </div>
  </div>

  <div class="activity-feed">
    <% @activities.each do |activity| %>
      <div class="activity-common">
        <div class="activity-header">
          <div clas="activity-userinfo">
            <div class="entry-avatar">
              <img src="" alt="Img">
            </div>
          </div>

          <div class="activity-date">
           <h5><%= activity.date_time.to_formatted_s(:short) %></h5>
          </div> 
          <div class="activity-title">
           <%= link_to activity do%>
              <h3><%= activity.title %></h3>
           <% end %> 
          </div> 
        </div> 
        <br>
        <div class="activity-d-t">
         <%= activity.elapsed_time.strftime('%I:%M:%S') %> /
         <%= activity.distance %> KM /
         <%= activity.elevation %> M
        </div>

        <div class="activity-a-m">
         <%= activity.avg_hr %> Avg /
         <%= activity.max_hr %> Max
        </div>

        <div class="activity-des">
         <p><%= activity.description %></p>
        </div>
      </div>
      <br>
    <% end %>

  </div>
  <!-- The point of this misc column is to add more technical data
  such as distance and training related, friends updates, clubs updates
  in small widgets -->
  <div class="activity-misc">
   <div class="activity-misc-title">
     <h4> New Event: </h4>
   </div>
  </div>
</div>



    
<%= link_to 'New Activity', new_activity_path %>
<br><br>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>
<br><br>

app/views/activities/show.html.erb
<div class="show-lay">
 <p>
   <div class="show-1">
     <strong></strong>
     <%= @activity.title %>
   </div>
 </p>

 <p>
   <div class="show">
     <strong>Date time:</strong>
     <%= @activity.date_time.to_formatted_s(:short) %>
   </div>
 </p>

 <p>
   <div class="show-3">
     <strong>Time:</strong>
     <%= @activity.elapsed_time.strftime('%I:%M:%S') %>
   </div>
 </p>

 <p>
   <div class="show-4">
     <strong>Distance:</strong>
     <%= @activity.distance %>
   
     <strong>Elevation:</strong>
     <%= @activity.elevation %>
   
     <strong>Effort:</strong>
     <%= @activity.effort %>
   </div>
 </p>

 <p>
   <div class="show-5">
     <strong>Average hr:</strong>
     <%= @activity.avg_hr %>

     <strong>Maximum hr:</strong>
     <%= @activity.max_hr %>
   </div>
 </p>

 <p>
   <div class="show-2">
     <strong>Description:</strong>
     <%= @activity.description %>
   </div>
 </p>
</div>

<br>
<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/home/welcome.html.erb
<br>
 <h1>Welcome</h1>

<div class="content-welc">
 <img height=300 src="https://ciclovivo.com.br/wp-content/uploads/2016/01/16709401_1417083658336970_568622001_o-696x464.jpg">

  <div class="text-welc">
   <h4>With O-Flow you can upload your activities and create your own training sessions, 
   you can also be invited by a club and participate in group training.
   Don't miss out on this opportunity to get your training to the highest level.</h4>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>

    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
 <div class="footer-oflow">
  <h3>O-Flow</h3></div>
 <div class="footer-menu">
  <ul>
   <li>
    <a href="#">Home</a>
   </li>
   <li>
    <a href="#">Terms</a>
   </li>
   <li>
    <a href="#">Privacy Policy</a>
   </li>
   <li>
    <a href="#">Help</a>
   </li>
  </ul></div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="border-bottom: 2px solid rgb(218, 118, 47);">

    <%= link_to root_path, class: "navbar-brand" do%>
        <img src="https://upload.wikimedia.org/wikipedia/commons/8/8c/Orienteering_symbol_framed.png" width="30" height="30" alt="">
        O-Flow
    <%end%>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to "New activity", new_activity_path, class: "nav-link" %>
                </li>

                <li class="nav-item">
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>

                <li class="nav-item">
                    <%= link_to "Activities", activities_path, class: "nav-link" %>
                </li>

            <% else %>
                <li class="nav-item">
                    <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                </li>
            <% end %>

        </ul>
    </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oflow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <!-- Bootstrap css below -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>





  </head>

  <body>
    <div id="page-container"> 
      <div id="content-wrap">
    <%= render 'layouts/header' %>
   <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>
    </div>
    <%= render 'layouts/footer' %>
    </div>
  </body>

</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.date_select :age %>
  </div>

  <div class="field">
    <%= form.label :nactionality %>
    <%= form.text_field :nactionality %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nactionality</th>
      <th>Gender</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.age %></td>
        <td><%= profile.nactionality %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.photo %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>

<p>
  <strong>Nactionality:</strong>
  <%= @profile.nactionality %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @profile.photo %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>